apiVersion: v1
kind: Service
metadata:
  name: prom-ingress
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: web
    port: 9090
    targetPort: 9090
  selector:
    prometheus: c756-kube-prometheus-stack-prometheus
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-ingress
spec:
  externalTrafficPolicy: Cluster
  type: LoadBalancer
  ports:
  - name: grafana
    port: 3000
    targetPort: 3000
  selector:
    app.kubernetes.io/name: grafana
