apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: cmpt756db
spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cmpt756db
  targetCPUUtilizationPercentage: 50