apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: cmpt756s2  
spec:
  maxReplicas: 3
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cmpt756s2-v1
  targetCPUUtilizationPercentage: 70